// <auto-generated />
using System;
using EntityCodeFirst2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityCodeFirst2.Migrations
{
    [DbContext(typeof(OyunDBContext))]
    partial class OyunDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityCodeFirst2.Models.Envanter", b =>
                {
                    b.Property<int>("EnvanterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvanterID"));

                    b.Property<double>("Fiyati")
                        .HasColumnType("float");

                    b.Property<double>("HitPower")
                        .HasColumnType("float");

                    b.Property<double>("IsabetOrani")
                        .HasColumnType("float");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MinXP")
                        .HasColumnType("float");

                    b.HasKey("EnvanterID");

                    b.ToTable("Envanterler");
                });

            modelBuilder.Entity("EntityCodeFirst2.Models.Oyuncu", b =>
                {
                    b.Property<int>("OyuncuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OyuncuID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyuncuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("XP")
                        .HasColumnType("float");

                    b.HasKey("OyuncuID");

                    b.ToTable("Oyuncular");
                });

            modelBuilder.Entity("EntityCodeFirst2.Models.Skor", b =>
                {
                    b.Property<int>("SkorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkorID"));

                    b.Property<int>("OyuncuID")
                        .HasColumnType("int");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("SkorID");

                    b.ToTable("Skorlar");
                });
#pragma warning restore 612, 618
        }
    }
}
